### ISSUE TITLE
Missing the minimum positive integer number in an array greater than cero

### ISSUE THREAD

**Issue by bookmebus** [bookmebus/coding-callenges#1]
Find a missing positive number inside an array, examples:
missing_number([30,1,2,3,2,2,6,4,9]) => 5
missing_number([1]) => nil
missing_number([20,-2,10]) => 1

**Comment by channainfo** [comment]
From the statement above, there can be possibilities: 
### That the number is not missing 
for example `[1]` => result is nil
### The number is missing by sorting
- the number missing in range for example [20,-2,10] -> [10..20] the min is 1

### Intersection
similar to the range problem missing in different range [30,1,2,3,2,2,6,4,9] which can be interpreted:

for each item in the array:
- 30: possible answer is [1..29]
- 1: [1..1] and 1 is the value of itself thus this item should be ignored
- 2: [1..2] should be ignored too since 2 is the value of itself and 1 has been ignored in the prior step
...
- 6: [1..5] but [1..3] has been ignored then the possible value is. [4..5]
- 4: [1..3] has been ignored and the 4 should be ignore from the last result ( [4..5] ) too. then the result should be modified to [5]
- 9: [1..8] since ignore since 5 is fitted in. since the 9 is the last item we found 5 as final result.

**Comment by channainfo** [comment]
## spec
```ruby
describe 'MissingMinPositiveNumberFinder' do
  describe 'shorted' do
    describe '#item is not missing' do
      it 'return nil for  [1]' do
        items = [1]
        finder = MissingMinPositiveNumberFinder.new(items)
        result = finder.run
        expect(result).to eq nil
      end

      it 'return nil for  [-20, -10]' do
        items = [-20,-10]
        finder = MissingMinPositiveNumberFinder.new(items, true)
        result = finder.run
        expect(result).to eq nil
      end
    end

    describe 'item is missing' do
      describe '#hard_sorted' do
        it 'return 7 for items = [30,1,2,3,2,5,6,4,9])' do
          items = [30,1,2,3,2,5,6,4,9]
          finder = MissingMinPositiveNumberFinder.new(items)
          result = finder.run
          expect(result).to eq 7
        end
      end
    
      describe 'soft_sorted' do
        it 'return 7 for items = [1, 2, 2, 3, 4, 5, 6, 9, 30])' do
          items = [1, 2, 2, 3, 4, 5, 6, 9, 30]
          finder = MissingMinPositiveNumberFinder.new(items, true)
          result = finder.run
          expect(result).to eq 7
        end
      end
    end
  end
end

```
